import type { Metadata } from "next";
import "./globals.css";
import { Switzer } from "./assets/fonts";
import { Layout } from "@/components/Layout";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <body className={Switzer.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
